print("Introduce tu peso en kg por favor: ")
peso=float(input())
print("Introduce tu altura en metros por favor (ej: 1.55) : ")
altura=float(input())
total= peso/(altura*altura)
print("Tu masa corporal es: " +str(total))
